dataset: linear_regression
dataset_params:
  n_dataset: 1e6
  # true_theta: 
  param_dim: 200
  bias: &bias_setting True 
  cov_type: random
  cov_const: 1.0
  # diag:
model: LinearRegression
model_params:
  bias: *bias_setting
radius: 1.0