inherits_from: mSNA_Avg_base.yaml
optimizer_params:
  batch_size: "expr: d"
  # Enable initial hessian inversion
  init_hess_inv: true
  # Number of samples to use for the estimation
  init_hess_inv_samples: "expr: int(10*d)" 
  # Regularization for the inversion
  init_hess_inv_reg: "expr: float(1e-4)"
