dataset: synthetic_linear_regression
dataset_params:
  n_dataset: 1e5
  # true_theta: 
  param_dim: 200
  bias: &bias_setting True 
  cov_type: identity
  # cov_const:
  # diag:
model: LinearRegression
model_params:
  bias: *bias_setting
radius: 1.0