dataset: synthetic_logistic_regression
dataset_params:
  n_dataset: 1e5
  # true_theta:
  param_dim: 100
  bias: &bias_setting True 
  cov_type: identity
  cov_const: 1.0
  # diag:
model: LogisticRegression
model_params:
  bias: *bias_setting
  lambda_: 0.0
radius: 1.0