dataset: mnist
dataset_params:
  # test_size is passed to the loader but ignored by the underlying mnist function,
  # which uses a standard 80/20 split.
  test_size: 0.2
  val_size: 0.0
  random_state: 0

model: LogisticRegression
model_params:
  bias: true
  lambda_: 1e-4 