inherits_from: StreamASGD.yaml
optimizer: "USNA"
optimizer_params:
  lr_hess_exp: 0.75
  lr_hess_const: 1.0
  lr_hess_add_iter: 0.0
  averaged_matrix: False
  compute_hessian_param_avg: False
  proj: True
  version: mask
  mask_size: 1
